#! /bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs debugfs /sys/kernel/debug
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /var
echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s
